### ISSUE TITLE
REST: Authentication: HTTP-Status 500

### ISSUE THREAD

**Issue by goot1** [h-mdm/hmdm-server#13]
When using the default REST-API to retrieve a bearer token, I'll get a http-status 500 error.

POST https://..../hmdm/rest/public/jwt/login

Exception Server:
==> localhost.2020-08-14.log <==
14-Aug-2020 19:27:55.545 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/hmdm] threw exception
        com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id_token" (class com.hmdm.rest.json.Response), not marked as ignorable (3 known properties: "status", "message", "data"])
 at [Source: (byte[])"{"id_token":"eyJh..."[truncated 2266 bytes]; line: 1, column: 14] (through reference chain: com.hmdm.rest.json.Response["id_token"])
                at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
                at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
                at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
                at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
                at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
                at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
                at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
                at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
                at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3266)
                at com.hmdm.plugins.audit.rest.filter.ResourceAuditor.getAuditLogRecord(ResourceAuditor.java:142)
                at com.hmdm.plugins.audit.rest.filter.AuditFilter.doFilter(AuditFilter.java:131)
                at com.hmdm.rest.filter.ApiOriginFilter.doFilter(ApiOriginFilter.java:52)
                at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
                at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:832)

I think it's because of the audit plugin when writing a AuditLog. - The objekt is a  serialized JWTToken an not a Response objekt.

ResourceAuditor.java Line 143
   final Response response = objectMapper.readValue(content, Response.class);

Workaround:
- Catch the exception in the client and read then the content and read the token

**Comment by h-mdm** [comment]
The issue has been fixed in version 3.23.4
